services:
  postgres:
    image: postgres:16-alpine
    container_name: backend-study-postgres
    environment:
      POSTGRES_USER: study
      POSTGRES_PASSWORD: study
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    container_name: backend-study-redis
    ports:
      - "6379:6379"

  keycloak:
    image: quay.io/keycloak/keycloak:26.7.0
    container_name: backend-study-keycloak
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8085:8080"
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import:ro
